# Generated by Django 5.2 on 2025-05-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeup_app', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
