# Generated by Django 5.1.7 on 2025-05-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup_app', '0006_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinquiry',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
